apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopkartx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Salim-0018/shopkartx.git
    targetRevision: main
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: shopkartx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
